language: haskell

notifications:
  email: false

install:
  cabal install --only-dependencies --enable-tests --force-reinstalls

script:
  cabal configure --enable-tests --enable-benchmark && cabal build && cabal test